name: 'AutoCoder'
description: 'This action automates the process of generating code from GitHub issues using OpenAIs ChatGPT and subsequently creates a pull request with the generated code for review.'
author: 'AlyonaKlekovkina'

inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication.'
    required: true
  REPOSITORY:
    description: 'Repository where the action will be executed (e.g., user/repo).'
    required: true
  ISSUE_NUMBER:
    description: 'Issue number that triggered the action.'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true
  SCRIPT_PATH:
    description: 'Path to the script that interacts with ChatGPT and generates code.'
    required: true
  LABEL:
    description: 'The label that triggers the action.'
    required: true
    default: 'autocoder-bot'

outputs:
  pull_request_url:
    description: 'The URL of the created pull request.'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        git config --global user.name "autocoder-bot"
        git config --global user.email "actions@github.com"
        mkdir -p autocoder-bot
      shell: bash

    - name: Greet Users
      run: echo "Hello, welcome to AutoCoder! Let's generate some code."
      shell: bash

    - name: Generate Code from Issue
      run: |
        chmod +x ${{ inputs.SCRIPT_PATH }}
        ${{ inputs.SCRIPT_PATH }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        REPOSITORY: ${{ inputs.REPOSITORY }}
        ISSUE_NUMBER: ${{ inputs.ISSUE_NUMBER }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        branch: autocoder-branch-${{ inputs.ISSUE_NUMBER }}
        title: "Autocoder: Code for issue #${{ inputs.ISSUE_NUMBER }}"
        body: "Automatically generated code for issue #${{ inputs.ISSUE_NUMBER }}"
        labels: ${{ inputs.LABEL }}
        commit-message: "Add code for issue #${{ inputs.ISSUE_NUMBER }}"
        committer: "autocoder-bot <actions@github.com>"
        author: "autocoder-bot <actions@github.com>"
