name: 'AutoCoder'
description: 'This action automates the process of generating code from GitHub issues using OpenAIs ChatGPT and subsequently creates a pull request with the generated code for review.'
author: 'AlyonaKlekovkina'

inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true
  REPOSITORY:
    description: 'Repository where the action will be executed (e.g., user/repo).'
    required: true
  ISSUE_NUMBER:
    description: 'Issue number that triggered the action.'
    required: true
  SCRIPT_PATH:
    description: 'Path to the script that interacts with ChatGPT and generates code.'
    required: true
  LABEL:
    description: 'The label assigned to GitHub issues that should be processed by the AutoCoder action. Only issues with this label will trigger the code generation process.'
    required: true
    default: 'autocoder-bot'

outputs:
  pull_request_url:
    description: 'The URL of the pull request that has been automatically created, containing the auto-generated code for review and potential merging.'

runs:
  using: 'composite'
  steps:
    - name: Greet Users
      run: echo "Hello, welcome to AutoCoder! Let's generate some code."
      shell: bash
      
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Git credentials
      run: |
        git config --global user.name "autocoder-bot"
        git config --global user.email "actions@github.com"
      shell: bash

    - name: Make script executable
      run: chmod +x ${{ inputs.SCRIPT_PATH }}
      shell: bash

    - name: Generate Code from Issue
      run: |
        bash ${{ inputs.SCRIPT_PATH }} ${{ inputs.GITHUB_TOKEN }} ${{ inputs.REPOSITORY }} ${{ inputs.ISSUE_NUMBER }} ${{ inputs.OPENAI_API_KEY }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}

    - name: Commit generated files
      run: |
        git add .
        git commit -m "Add generated code for issue #${{ inputs.ISSUE_NUMBER }}"
        git push origin HEAD:autocoder-branch-${{ inputs.ISSUE_NUMBER }}
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        branch: autocoder-branch-${{ inputs.ISSUE_NUMBER }}
        title: "Autocoder generated code for issue #${{ inputs.ISSUE_NUMBER }}"
        body: "This pull request includes code automatically generated for issue #${{ inputs.ISSUE_NUMBER }}."
        labels: ${{ inputs.LABEL }}
        commit-message: "Add code for issue #${{ inputs.ISSUE_NUMBER }}"
        committer: "autocoder-bot <actions@github.com>"
        author: "autocoder-bot <actions@github.com>"
