name: 'AutoCoder'
description: 'This action automates the process of generating code from GitHub issues using OpenAIs ChatGPT and subsequently creates a pull request with the generated code for review.'
author: 'AlyonaKlekovkina'

inputs:
  github_token:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
  repository:
    description: 'Repository where the action will be executed (e.g., user/repo).'
    required: true
  issue_number:
    description: 'Issue number that triggered the action.'
    required: true
  openai_api_key:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true
  script_path:
    description: 'Path to the script that interacts with ChatGPT and generates code.'
    required: true
  label:
    description: 'The label assigned to GitHub issues that should be processed by the AutoCoder action. Only issues with this label will trigger the code generation process.'
    required: true
    default: 'autocoder-bot'

outputs:
  pull_request_url:
    description: 'The URL of the pull request that has been automatically created, containing the auto-generated code for review and potential merging.'

runs:
  using: 'composite'
    steps:
    - name: Greet Users
      run: echo "Hello, welcome to AutoCoder! Let's generate some code."
      shell: bash
    - name: Generate Code from Issue
      run: |
        # The script that interacts with ChatGPT and generates code goes here.
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    - name: Create Pull Request
      run: |
        chmod +x ${{ inputs.script_path }}
      shell: bash
      env:
        github_token: ${{ inputs.github_token }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Git identity
      run: |
        git config --global user.name "autocoder-bot"
        git config --global user.email "actions@github.com"
      shell: bash
    
    - name: Create output directory
      run: mkdir -p autocoder-bot
      

    - name: Commit generated files
      run: |
        git add .
        git commit -m "Add generated code for issue #${{ inputs.issue_number }}"
        git push origin HEAD:autocoder-branch-${{ inputs.issue_number }}
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.github_token }}
        branch: autocoder-branch-${{ inputs.issue_number }}
        title: "Autocoder generated code for issue #${{ inputs.issue_number }}"
        body: "This pull request includes code automatically generated for issue #${{ inputs.issue_number }}."
        labels: ${{ inputs.label }}
        commit-message: "Add code for issue #${{ inputs.issue_number }}"
        committer: "autocoder-bot <actions@github.com>"
        author: "autocoder-bot <actions@github.com>"
