name: Access Issue Information
on:
  issues:
    types: [opened, reopened]

jobs:
  access_issue_info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code
      - name: Print Issue Information
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
