name: Access Issue Information

on: 
  issues: 
    types: [opened, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  access_issue_info:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p autocoder-bot
        
      - name: Make script executable
        run: chmod +x ./scripts/script.sh


      - name: Generate Code with ChatGPT
        id: generate_code
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: AlyonaKlekovkina/AutoCoder
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
        run: ./scripts/script.sh ${{ secrets.GITHUB_TOKEN }} ${{ env.REPOSITORY }} ${{ env.ISSUE_NUMBER }} ${{ secrets.OPENAI_API_KEY }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot/
          
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:  
          name: autocoder-artifact
          path: autocoder-artifact/
          
      - name: Display Generated Code using the ls command
        run: ls -R autocoder-artifact/

      - name: Configure Git
        run: |
          git config user.name "autocoder-bot"
          git config user.email "actions@github.com"

      - name: Create new branch
        run: |
          git checkout -b autocoder-branch-${{ github.event.issue.number }}

      - name: Copy generated files into repo
        run: |
          cp -r autocoder-artifact/* .      

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: autocoder-branch-${{ github.event.issue.number }}
          title: "Autocoder generated code for issue #${{ github.event.issue.number }}"
          body: "This pull request includes code automatically generated for issue #${{ github.event.issue.number }}."
          labels: autocoder-bot
