name: AutoCodeGen

on:
  issues:
    types: [labeled, opened, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  generate_code:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: AutoCoder Action
        uses: AlyonaKlekovkina/Autocoder@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SCRIPT_PATH: ./scripts/script.sh
          LABEL: 'autocoder-bot'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: autocoder-branch-${{ github.event.issue.number }}
          title: "Autocoder generated code for issue #${{ github.event.issue.number }}"
          body: "This pull request includes code automatically generated for issue #${{ github.event.issue.number }}."
          labels: autocoder-bot
          committer: "autocoder-bot <actions@github.com>"
          author: "autocoder-bot <actions@github.com>"
