name: Access Issue Information

on: 
  issues: 
    types: [opened, reopened]

jobs:
  access_issue_info:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Code with ChatGPT
        id: generate_code
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: AlyonaKlekovkina/AutoCoder
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: sudo +x ./scripts/script.sh
      - name: Upload Artifact
        run: |
          if [[ "$ISSUE_LABLE" = 'autocoder-bot' ]]; then
            echo "Issue lable detected"
          fi
