name: Access Issue Information

on: 
  issues: 
    types: [opened, reopened, labeled]

jobs:
  access_issue_info:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p autocoder-bot
        
      - name: Make script executable
        run: chmod +x ./scripts/script.sh


      - name: Generate Code with ChatGPT
        id: generate_code
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: AlyonaKlekovkina/AutoCoder
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
        run: ./scripts/script.sh ${{ env.GITHUB_TOKEN }} ${{ env.REPOSITORY }} ${{ env.ISSUE_NUMBER }} ${{ env.OPENAI_API_KEY }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot/
          
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:  
          name: autocoder-artifact
          path: autocoder-artifact/
          
      - name: Display Generated Code using the ls command
        run: |
          find autocoder-artifact/ -type f -exec ls -l {} \;
