name: Access Issue Information
on:
  issues:
    types: [opened, reopened, labeled]
jobs:
  access_issue_info:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    steps:
      # First checkout the repository to access the script
      - name: Checkout repository
        uses: actions/checkout@v3

      # Explicit step just for making script executable
      - name: Make script executable
        run: |
          chmod +x ./scripts/script.sh
          ls -la ./scripts/script.sh  # Optional verification

      - name: Generate Code with ChatGPT
        id: generate_code
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            REPOSITORY: ${{ github.repository }}
            ISSUE_NUMBER: ${{ github.event.issue.number }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
        run: ./scripts/script.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: autocoder-artifact
          path: autocoder-artifact/*

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: autocoder-artifact
          path: downloaded-artifact

      - name: List generated files
        run: |
          echo "Listing all generated files recursively:"
          find autocoder-artifact-download -type f -exec ls -la {} \;
