name: Autocoder Bot
on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  generate-code:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make script executable
        run: chmod +x ./scripts/script.sh

      - name: Generate Code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/script.sh "$GITHUB_TOKEN" "$ISSUE_NUMBER" "$OPENAI_API_KEY"

      - name: Set up Git config
        run: |
          git config --global user.name "autocoder-bot"
          git config --global user.email "actions@github.com"

      - name: Create branch and commit changes
        run: |
          git checkout -b autocoder-branch-${{ github.event.issue.number }}
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Autogenerated code for issue #${{ github.event.issue.number }}"
            git push origin autocoder-branch-${{ github.event.issue.number }}
          fi

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: autocoder-branch-${{ github.event.issue.number }}
          delete-branch: false
          base: main
          labels: autocoder-bot
          title: "Autocoder: Fix for issue #${{ github.event.issue.number }}"
          body: "Automated code generation from issue #${{ github.event.issue.number }}"
          commit-message: "Autogenerated code for issue #${{ github.event.issue.number }}"
