name: Autocoder Bot
on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  generate-code:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make script executable
        run: chmod +x ./scripts/script.sh

      - name: Generate Code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          ./scripts/script.sh "$GITHUB_TOKEN" "$ISSUE_NUMBER" "$OPENAI_API_KEY"
          echo "Generated files:"
          ls -la

      - name: Commit and Push Changes
        run: |
          git config --global user.name "autocoder-bot"
          git config --global user.email "actions@github.com"
          git checkout -b autocoder-branch-${{ github.event.issue.number }}
          git add .
          git status
          git commit -m "Autogenerated code for issue #${{ github.event.issue.number }}"
          git push origin autocoder-branch-${{ github.event.issue.number }}
          echo "Pushed branch autocoder-branch-${{ github.event.issue.number }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        id: pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: autocoder-branch-${{ github.event.issue.number }}
          base: main
          labels: autocoder-bot
          title: "Autocoder: Fix for issue #${{ github.event.issue.number }}"
          body: "Automated code generation from issue"
          commit-message: "Autogenerated code for issue #${{ github.event.issue.number }}"
          draft: false

      - name: Verify PR Creation
        run: |
          echo "PR Number: ${{ steps.pr.outputs.pull-request-number }}"
          echo "PR URL: ${{ steps.pr.outputs.pull-request-url }}"
