name: AutoCodeGen

on:
  issues:
    types: [labeled, opened, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  generate_code:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')

    steps:
      - name: Run AutoCoder Action
        uses: AlyonaKlekovkina/AutoCoder@v1.0.0
        with:
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SCRIPT_PATH: ./scripts/script.sh
          LABEL: 'autocoder-bot'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up git identity and environment
        run: |
          git config --global user.name "autocoder-bot"
          git config --global user.email "actions@github.com"
          mkdir -p autocoder-bot

      - name: Create output directory
        run: mkdir -p autocoder-bot

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot/

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-artifact/

      - name: Display Generated Code using the ls command
        run: ls -R autocoder-artifact/

      - name: Copy generated files into repo
        run: |
          cp -r autocoder-artifact/* .

      - name: Commit generated code
        run: |
          git add .
          git commit -m "Autocoder generated code for issue #${{ inputs.ISSUE_NUMBER }}"
