name: AutoCodeGen

on:
  issues:
    types: [labeled, opened, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  generate_code:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')

    steps:
      - name: Run AutoCoder Action
        uses: AlyonaKlekovkina/AutoCoder@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SCRIPT_PATH: ./scripts/script.sh
          LABEL: 'autocoder-bot'
