name: Access Issue Information
on:
  issues:
    types: [opened, reopened, labeled]


jobs:
  access_issue_info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check issue label
        id: check_label
        run: |
          echo "IS_AUTOCODER_BOT_LABEL=$(echo '${{ join(github.event.issue.labels.*.name, ', ') }}' | grep -w 'autocoder-bot' > /dev/null && echo 'true' || echo 'false')" >> $GITHUB_ENV
      
      - name: Generate Code with ChatGPT
        id: generate_code
        if: env.IS_AUTOCODER_BOT_LABEL == 'true'
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            REPOSITORY: AlyonaKlekovkina/AutoCoder
            ISSUE_NUMBER: ${{ github.event.issue.number }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
        run: |
          chmod +x scripts/script.sh
          ./scripts/script.sh

      - name: Upload Artifact
        id: upload_artifact
        uses: actions/upload-artifact@v3
        with:
            name: autocoder-artifact
            path: autocoder-artifact/*
            
      - name: Downloading artifact to the home directory
        uses: actions/download-artifact@v3
        with:
          name: autocoder-artifact
          path: ~/autocoder-artifact

      - name: Display Generated Code using the ls command
        run: ls -l ~/autocoder-artifact
