name: Access Issue Information
on:
  issues:
    types: [opened, reopened]


jobs:
  access_issue_info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code
      - name: Print Issue Information
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: AlyonaKlekovkina/AutoCoder
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_ASSIGNEES: ${{ join(github.event.issue.assignees.*.login, ', ') }}
          ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
        run: |
          echo "Issue Number: ${ISSUE_NUMBER}"
          echo "Issue Title: ${ISSUE_TITLE}"
          echo "Issue Body: ${ISSUE_BODY}"
          echo "Issue Assignees: ${ISSUE_ASSIGNEES}"
          echo "Issue Labels: ${ISSUE_LABELS}"
