name: First Workflow    
                                         
on: push   
                                               
jobs:
                         
  first-job:                           
    name: say_hello                    
    runs-on: ubuntu-latest                           
    steps:

      #step 1                           
      - name: Print a greeting                             
        run: echo "Hello, world"
      - uses: actions/checkout@v2
